"""Formations counters turns and history for positions

Revision ID: 14da3a3a49b
Revises: 5b962db163
Create Date: 2014-12-15 15:55:44.418316

"""

# revision identifiers, used by Alembic.
revision = '14da3a3a49b'
down_revision = '5b962db163'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_shpclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cclas', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cclas'], ['t_shpclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cgam', sa.Integer(), nullable=True),
    sa.Column('cturn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cgam'], ['t_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cplay', sa.Integer(), nullable=True),
    sa.Column('ccou', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccou'], ['t_counters.id'], ),
    sa.ForeignKeyConstraint(['cplay'], ['t_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_h_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cclas', sa.Integer(), nullable=True),
    sa.Column('ccou', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('cturn', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cclas'], ['t_shpclasses.id'], ),
    sa.ForeignKeyConstraint(['ccou'], ['t_counters.id'], ),
    sa.ForeignKeyConstraint(['cturn'], ['t_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_h_counter')
    op.drop_table('t_formations')
    op.drop_table('t_turns')
    op.drop_table('t_counters')
    op.drop_table('t_shpclasses')
    ### end Alembic commands ###
