"""Initial nigration

Revision ID: 153f31c4339
Revises: None
Create Date: 2014-12-11 00:06:49.883738

"""

# revision identifiers, used by Alembic.
revision = '153f31c4339'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('mail', sa.String(length=75), nullable=True),
    sa.Column('passwdhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a_approle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('r_arousr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capr', sa.Integer(), nullable=True),
    sa.Column('cuse', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capr'], ['a_approle.id'], ),
    sa.ForeignKeyConstraint(['cuse'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_arousr')
    op.drop_table('a_approle')
    op.drop_table('t_users')
    ### end Alembic commands ###
