"""Initial migration

Revision ID: 27da8c943d9
Revises: None
Create Date: 2014-12-16 16:40:59.066127

"""

# revision identifiers, used by Alembic.
revision = '27da8c943d9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acro', sa.String(length=15), nullable=True),
    sa.Column('desc', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a_approle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a_shpclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acro', sa.String(length=15), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('mail', sa.String(length=75), nullable=True),
    sa.Column('passwdhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cgam', sa.Integer(), nullable=True),
    sa.Column('cturn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cgam'], ['t_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cgam', sa.Integer(), nullable=True),
    sa.Column('cuse', sa.Integer(), nullable=True),
    sa.Column('csid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cgam'], ['t_games.id'], ),
    sa.ForeignKeyConstraint(['csid'], ['a_sides.id'], ),
    sa.ForeignKeyConstraint(['cuse'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usergame', 't_players', ['cuse', 'cgam'], unique=True)
    op.create_table('r_arousr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capr', sa.Integer(), nullable=True),
    sa.Column('cuse', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capr'], ['a_approle.id'], ),
    sa.ForeignKeyConstraint(['cuse'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cclas', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cclas'], ['a_shpclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_h_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cclas', sa.Integer(), nullable=True),
    sa.Column('ccou', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('cturn', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cclas'], ['a_shpclasses.id'], ),
    sa.ForeignKeyConstraint(['ccou'], ['t_counters.id'], ),
    sa.ForeignKeyConstraint(['cturn'], ['t_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_formations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cplay', sa.Integer(), nullable=True),
    sa.Column('ccou', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ccou'], ['t_counters.id'], ),
    sa.ForeignKeyConstraint(['cplay'], ['t_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_formations')
    op.drop_table('t_h_counter')
    op.drop_table('t_counters')
    op.drop_table('r_arousr')
    op.drop_index('idx_usergame', table_name='t_players')
    op.drop_table('t_players')
    op.drop_table('t_turns')
    op.drop_table('t_users')
    op.drop_table('t_games')
    op.drop_table('a_shpclasses')
    op.drop_table('a_approle')
    op.drop_table('a_sides')
    ### end Alembic commands ###
