"""Basic Player/Game structure

Revision ID: 5b962db163
Revises: 153f31c4339
Create Date: 2014-12-12 00:38:10.651420

"""

# revision identifiers, used by Alembic.
revision = '5b962db163'
down_revision = '153f31c4339'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cgam', sa.Integer(), nullable=True),
    sa.Column('cuse', sa.Integer(), nullable=True),
    sa.Column('csid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usergame', 't_players', ['cuse', 'cgam'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usergame', table_name='t_players')
    op.drop_table('t_players')
    op.drop_table('t_games')
    op.drop_table('a_sides')
    ### end Alembic commands ###
